name: multi_language_currency_app
description: "This is the project for uni of multi-currency."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  carousel_slider: ^4.0.0

  # Firebase Core
  firebase_core: ^3.8.0

  # Firebase Authentication (for user sign-in and sign-up)
  firebase_auth: ^5.3.3

  # Firebase Cloud Firestore (for database functionality)
  cloud_firestore: ^5.5.0
  # Localization support

  # Firebase Analytics (optional, for app analytics)
  firebase_analytics: ^11.3.0

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Add assets here
  assets:
    - assets/images/download.jpg
    - assets/images/